
export const spellsMaster = {
  bard: {
    "Chant of Battle": 1,
    "Chords of Dissonance": 2,
    "Jaxan's Jig o' Vigor": 3,
    "Lyssa's Locating Lyric": 4,
    "Selo's Accelerando": 5,
    "Hymn of Restoration": 6,
    "Jonthan's Whistling": 7,
    "Kelin's Lugubrious Lament": 8,
    "Elemental Rhythms": 9,
    "Anthem De Arms": 10,
    "Cinda's Charismatic Carillon": 11,
    "Brusco's Boastful Bellow": 12,
    "Purifying Rhythms": 13,
    "Lyssa's Cataloging": 14,
    "Kelin's Lucid Lullaby": 15,
    "Tarew's Aquatic Ayre": 16,
    "Guardian Rhythms": 17,
    "Denon's Disruptive Discord": 18,
    "Shauri's Sonorous Clouding": 19,
    "Largo's Melodic Binding": 20,
    "Cassindra's Chant of Clarity": 20,
    "Melanie's Mellifluous Motion": 21,
    "Alenia's Disenchanting Melody": 22,
    "Selo's Consonant Chain": 23,
    "Lyssa's Veracious Concord": 24,
    "Psalm of Warmth": 25,
    "Angstlich's Appalling Screech": 26,
    "Solon's Song of the Sirens": 27,
    "Crission's Pixie Strike": 28,
    "Psalm of Vitality": 29,
    "Fufil's Curtailing Chant": 30,
    "Agilmente's Aria of Eagles": 31,
    "Cassindra's Chorus of Clarity": 32,
    "Psalm of Cooling": 33,
    "Cantana of Soothing": 34,
    "Lyssa's Solidarity of Vision": 34,
    "Denon's Dissension": 35,
    "Vilia's Verses of Celerity": 36,
    "Psalm of Purity": 37,
    "Tuyen's Chant of Flame": 38,
    "Solon's Bewitching Bravura": 39,
    "Syvelian's Anti-Magic Aria": 40,
    "Psalm of Mystic Shielding": 41,
    "McVaxius' Berserker Crescendo": 42,
    "Denon's Desperate Dirge": 43,
    "Cassindra's Elegy": 44,
    "Jonthan's Provocation": 45,
    "Tuyen's Chant of Frost": 46,
    "Niv's Melody of Preservation": 47,
    "Selo's Chords of Cessation": 48,
    "Shield of Song": 49,
    "Verses of Victory": 50,
    "Melody of Ervaj": 50,
    "Selo's Song of Travel": 51,
    "Largo's Absonant Binding": 51,
    "Nillipus' March of the Wee": 52,
    "Song of Twilight": 53,
    "Song of Dawn": 53,
    "Vilia's Chorus of Celerity": 54,
    "Selo's Assonant Strane": 54,
    "Cantata of Replenishment": 55,
    "Brusco's Bombastic Bellow": 55,
    "Occlusion of Sound": 55,
    "Song of Highsun": 56,
    "Song of Midnight": 56,
    "McVaxius' Rousing Rondo": 57,
    "Cassindra's Insipid Ditty": 57,
    "Niv's Harmonic": 58,
    "Jonthan's Inspiration": 58,
    "Denon's Bereavement": 59,
    "Solon's Charismatic Concord": 59,
    "Kazumi's Note of Preservation": 60,
    "Angstlich's Assonance": 60,
    "Composition of Ervaj": 60
  },
  cleric: {
    "Courage": 1,
    "Cure Poison": 1,
    "Divine Aura": 1,
    "Flash of Light": 1,
    "Lull": 1,
    "Minor Healing": 1,
    "Spook the Dead": 1,
    "Strike": 1,
    "True North": 1,
    "Yaulp": 1,
    "Cure Blindness": 5,
    "Cure Disease": 5,
    "Furor": 5,
    "Gate": 5,
    "Holy Armor": 5,
    "Light Healing": 5,
    "Reckless Strength": 5,
    "Stun": 5,
    "Summon Drink": 5,
    "Ward Undead": 5,
    "Center": 9,
    "Endure Fire": 9,
    "Endure Poison": 9,
    "Fear": 9,
    "Hammer of Wrath": 9,
    "Invigor": 9,
    "Root": 9,
    "Sense the Dead": 9,
    "Soothe": 9,
    "Summon Food": 9,
    "Word of Pain": 9,
    "Bind Affinity": 14,
    "Cancel Magic": 14,
    "Endure Cold": 14,
    "Endure Disease": 14,
    "Expulse Undead": 14,
    "Halo of Light": 14,
    "Healing": 14,
    "Invisibility versus Undead": 14,
    "Sense Summoned": 14,
    "Smite": 14,
    "Symbol of Transal": 14,
    "Calm": 19,
    "Daring": 19,
    "Endure Magic": 19,
    "Extinguish Fatigue": 19,
    "Holy Might": 19,
    "Spirit Armor": 19,
    "Ward Summoned": 19,
    "Word of Shadow": 19,
    "Yaulp II": 19,
    "Bravery": 24,
    "Counteract Poison": 24,
    "Dismiss Undead": 24,
    "Greater Healing": 24,
    "Hammer of Striking": 24,
    "Inspire Fear": 24,
    "Symbol of Ryltan": 24,
    "Wave of Fear": 24,
    "Abundant Drink": 29,
    "Counteract Disease": 29,
    "Divine Barrier": 29,
    "Enstill": 29,
    "Expulse Summoned": 29,
    "Guard": 29,
    "Imbue Amber": 29,
    "Imbue Black Pearl": 29,
    "Imbue Black Sapphire": 29,
    "Imbue Diamond": 29,
    "Imbue Emerald": 29,
    "Imbue Opal": 29,
    "Imbue Peridot": 29,
    "Imbue Plains Pebble": 29,
    "Imbue Rose Quartz": 29,
    "Imbue Ruby": 29,
    "Imbue Sapphire": 29,
    "Imbue Topaz": 29,
    "Panic the Dead": 29,
    "Revive": 29,
    "Word of Spirit": 29,
    "Wrath": 29,
    "Abundant Food": 29,
    "Armor of Protection": 29,
    "Atone": 34,
    "Blinding Luminance": 34,
    "Expel Undead": 34,
    "Force": 34,
    "Frenzied Strength": 34,
    "Resist Fire": 34,
    "Resist Poison": 34,
    "Superior Healing": 34,
    "Symbol of Pinzarn": 34,
    "Tremor": 34,
    "Valor": 34,
    "Word of Health": 34,
    "Armor of Faith": 39,
    "Complete Healing": 39,
    "Dismiss Summoned": 39,
    "Invoke Fear": 39,
    "Nullify Magic": 39,
    "Pacify": 39,
    "Resist Cold": 39,
    "Resist Disease": 39,
    "Resuscitate": 39,
    "Turning of the Unnatural": 39,
    "Word of Souls": 39,
    "Banish Undead": 44,
    "Celestial Healing": 44,
    "Earthquake": 44,
    "Hammer of Requital": 44,
    "Resist Magic": 44,
    "Resolution": 44,
    "Retribution": 44,
    "Symbol of Naltron": 44,
    "Yaulp III": 44,
    "Abolish Poison": 49,
    "Expel Summoned": 49,
    "Immobilize": 49,
    "Resurrection": 49,
    "Shield of Words": 49,
    "Sound of Force": 49,
    "Word Divine": 49,
    "Word of Healing": 49,
    "Improved Invis to Undead": 50,
    "Death Pact": 51,
    "Dread of Night": 51,
    "Remedy": 51,
    "Sunskin": 51,
    "Heroic Bond": 52,
    "Heroism": 52,
    "Upheaval": 52,
    "Word of Vigor": 52,
    "Annul Magic": 53,
    "Divine Light": 53,
    "Yaulp IV": 53,
    "Reckoning": 54,
    "Symbol of Marzin": 54,
    "Unswerving Hammer of Faith": 54,
    "Exile Undead": 55,
    "Fortitude": 55,
    "Stun Command": 55,
    "Wake of Tranquility": 55,
    "Banish Summoned": 56,
    "Mark of Karn": 56,
    "Paralyzing Earth": 56,
    "Reviviscence": 56,
    "Aegis": 57,
    "Bulwark of Faith": 57,
    "Trepidation": 57,
    "Word of Restoration": 57,
    "Antidote": 58,
    "Enforced Reverence": 58,
    "Naltron's Mark": 58,
    "Celestial Elixir": 59,
    "The Unspoken Word": 59,
    "Aegolism": 60,
    "Banishment of Shadows": 60,
    "Divine Intervention": 60,
    "Word of Redemption": 60
  },
  druid: {
    'Burst of Flame': 1,
    'Dance of the Fireflies': 1,
    'Endure Fire': 1,
    'Flame Lick': 1,
    'Lull Animal': 1,
    'Minor Healing': 1,
    'Panic Animal': 1,
    'Sense Animals': 1,
    'Skin like Wood': 1,
    'Snare': 1,
    'Burst of Fire': 5,
    'Camouflage': 5,
    'Cure Disease': 5,
    'Cure Poison': 5,
    'Gate': 5,
    'Grasping Roots': 5,
    'Harmony': 5,
    'Invoke Lightning': 5,
    'Ward Summoned': 5,
    'Whirling Wind': 5,
    'Endure Cold': 9,
    'Enduring Breath': 9,
    'Firefist': 9,
    'Ignite': 9,
    'Invisibility versus Animals': 9,
    'Light Healing': 9,
    'Shield of Thistles': 9,
    'Starshine': 9,
    'Strength of Earth': 9,
    'Thistlecoat': 9,
    'Treeform': 9,
    'Befriend Animal': 14,
    'Bind Affinity': 14,
    'Cascade of Hail': 14,
    'Expulse Summoned': 14,
    'Halo of Light': 14,
    'Invigor': 14,
    'Levitate': 14,
    'See Invisible': 14,
    'Skin Like Rock': 14,
    'Spirit of Wolf': 14,
    'Stinging Swarm': 14,
    'Summon Drink': 14,
    'Summon Food': 14,
    'Barbcoat': 19,
    'Calm Animal': 19,
    'Cancel Magic': 19,
    'Careless Lightning': 19,
    'Dizzying Wind': 19,
    'Endure Disease': 19,
    'Endure Poison': 19,
    'Feral Spirit': 19,
    'Healing': 19,
    'Ring of Butcher': 19,
    'Ring of Commons': 19,
    'Ring of Karana': 19,
    'Ring of Surefall Glade': 19,
    'Ring of Toxxulia': 19,
    'Shield of Barbs': 19,
    'Superior Camouflage': 19,
    'Terrorize Animal': 19,
    'Charm Animals': 24,
    'Creeping Crud': 24,
    'Dismiss Summoned': 24,
    'Ensnaring Roots': 24,
    'Pogonip': 24,
    'Resist Fire': 24,
    'Ring of Feerrott': 24,
    'Ring of Lavastorm': 24,
    'Ring of Ro': 24,
    'Ring of Steamfont': 24,
    'Ring of the Combines': 24,
    'Scale of Wolf': 24,
    'Skin Like Steel': 24,
    'Spirit of Cheetah': 24,
    'Sunbeam': 24,
    'Tremor': 24,
    'Wolf Form': 24,
    'Beguile Plants': 29,
    'Bramblecoat': 29,
    'Circle of Butcher': 29,
    'Circle of Commons': 29,
    'Circle of Karana': 29,
    'Circle of Surefall Glade': 29,
    'Circle of Toxxulia': 29,
    'Combust': 29,
    'Counteract Disease': 29,
    'Counteract Poison': 29,
    'Ensnare': 29,
    'Extinguish Fatigue': 29,
    'Greater Healing': 29,
    'Imbue Emerald': 29,
    'Imbue Plains Pebble': 29,
    'Immolate': 29,
    'Ring of Misty': 29,
    'Shield of Brambles': 29,
    'Succor: East': 29,
    'Beguile Animals': 34,
    'Circle of Feerrott': 34,
    'Circle of Iceclad': 34,
    'Circle of Lavastorm': 34,
    'Circle of Ro': 34,
    'Circle of Steamfont': 34,
    'Circle of the Combines': 34,
    'Drones of Doom': 34,
    'Earthquake': 34,
    'Endure Magic': 34,
    'Expel Summoned': 34,
    'Fury of Air': 34,
    'Greater Wolf Form': 34,
    'Lightning Strike': 34,
    'Regeneration': 34,
    'Resist Cold': 34,
    'Ring of Great Divide': 34,
    'Ring of Iceclad': 34,
    'Strength of Stone': 34,
    'Succor: Butcher': 34,
    'Avalanche': 39,
    'Circle of Great Divide': 39,
    'Circle of Misty': 39,
    'Enveloping Roots': 39,
    'Firestrike': 39,
    'Pack Regeneration': 39,
    'Pack Spirit': 39,
    'Ring of Cobalt Scar': 39,
    'Ring of Wakening Lands': 39,
    "Ro's Fiery Sundering": 39,
    'Share Wolf Form': 39,
    'Shield of Spikes': 39,
    'Skin like Diamond': 39,
    'Spikecoat': 39,
    'Succor: Ro': 39,
    'Wind of the North': 39,
    'Wind of the South': 39,
    'Allure of the Wild': 44,
    'Banish Summoned': 44,
    'Calefaction': 44,
    'Chloroplast': 44,
    'Circle of Cobalt Scar': 44,
    'Circle of Wakening Lands': 44,
    'Drifting Death': 44,
    'Fixation of Ro': 44,
    'Form of the Great Wolf': 44,
    'Nullify Magic': 44,
    'Resist Disease': 44,
    'Resist Poison': 44,
    'Savage Spirit': 44,
    'Storm Strength': 44,
    'Succor: Lavastorm': 44,
    'Engulfing Roots': 49,
    'Fire': 49,
    'Ice': 49,
    'Lightning Blast': 49,
    'Pack Chloroplast': 49,
    'Resist Magic': 49,
    'Shield of Thorns': 49,
    'Skin like Nature': 49,
    'Starfire': 49,
    'Succor: North': 49,
    'Thorncoat': 49,
    'Improved Superior Camouflage': 50,
    'Circle of Winter': 51,
    'Legacy of Spike': 51,
    'Repulse Animal': 51,
    'Superior Healing': 51,
    'Upheaval': 51,
    'Breath of Ro': 52,
    'Call of Karana': 52,
    'Circle of Summer': 52,
    'Egress': 52,
    'Glamour of Tunare': 53,
    'Spirit of Scale': 53,
    'Winged Death': 53,
    'Blizzard': 54,
    'Form of the Howler': 54,
    'Regrowth': 54,
    'Scoriae': 54,
    'Annul Magic': 55,
    'Chloroblast': 55,
    'Exile Summoned': 55,
    'Girdle of Karana': 55,
    'Nature Walkers Behest': 55,
    "Tunare's Request": 55,
    'Bladecoat': 56,
    'Breath of Karana': 56,
    'Engorging Roots': 56,
    'Wake of Karana': 56,
    'Bonds of Tunare': 57,
    'Frost': 57,
    'Natureskin': 57,
    'Succor': 57,
    'Fist of Karana': 58,
    'Regrowth of the Grove': 58,
    'Shield of Blades': 58,
    'Legacy of Thorn': 59,
    'Spirit of Oak': 59,
    'Wildfire': 59,
    'Banishment': 60,
    'Entrapping Roots': 60,
    'Form of the Hunter': 60,
    'Mask of the Hunter': 60,
    "Nature's Touch": 60,
    'Protection of the Glades': 60
  },
  enchanter: {
    'Lull': 1,
    'Minor Illusion': 1,
    'Minor Shielding': 1,
    "Pendril's Animation": 1,
    'Reclaim Energy': 1,
    'Shallow Breath': 1,
    'Strengthen': 1,
    'Taper Enchantment': 1,
    'True North': 1,
    'Weaken': 1,
    'Color Flux': 4,
    'Enfeeblement': 4,
    'Fear': 4,
    'Gate': 4,
    'Haze': 4,
    'Illusion: Half-Elf': 4,
    'Illusion: Human': 4,
    'Invisibility': 4,
    "Juli`s Animation": 4,
    'Mesmerize': 4,
    'Suffocating Sphere': 4,
    'Tashan': 4,
    'Alliance': 8,
    'Bind Sight': 8,
    'Cancel Magic': 8,
    'Chaotic Feedback': 8,
    'Enchant Clay': 8,
    'Enchant Silver': 8,
    'Eye of Confusion': 8,
    'Illusion: Gnome': 8,
    'Illusion: Wood': 8,
    'Lesser Shielding': 8,
    "Mircyl's Animation": 8,
    'Root': 8,
    'See Invisible': 8,
    'Sentinel': 8,
    'Soothe': 8,
    'Bind Affinity': 12,
    'Charm': 12,
    'Choke': 12,
    'Ebbing Strength': 12,
    'Enduring Breath': 12,
    'Illusion: Dark Elf': 12,
    'Illusion: Erudite': 12,
    'Illusion: Halfling': 12,
    'Illusion: High Elf': 12,
    "Kilan`s Animation": 12,
    'Languid Pace': 12,
    'Memory Blur': 12,
    'Mist': 12,
    'Thicken Mana': 12,
    'Whirl Till You Hurl': 12,
    'Breeze': 16,
    'Chase the Moon': 16,
    'Disempower': 16,
    'Enchant Electrum': 16,
    'Enthrall': 16,
    'Identify': 16,
    'Illusion: Barbarian': 16,
    'Illusion: Dwarf': 16,
    'Illusion: Tree': 16,
    'Invisibility versus Undead': 16,
    'Levitate': 16,
    'Mesmerization': 16,
    'Quickness': 16,
    'Rune I': 16,
    'Sanity Warp': 16,
    "Shalee`s Animation": 16,
    'Shielding': 16,
    'Benevolence': 20,
    'Berserker Strength': 20,
    'Calm': 20,
    'Cloud': 20,
    'Crystallize Mana': 20,
    'Endure Magic': 20,
    'Feckless Might': 20,
    'Illusion: Iksar': 20,
    'Illusion: Ogre': 20,
    'Illusion: Troll': 20,
    'Shifting Sight': 20,
    "Sisna`s Animation": 20,
    'Sympathetic Aura': 20,
    'Tashani': 20,
    'Alacrity': 24,
    'Beguile': 24,
    'Chaos Flux': 24,
    'Enchant Gold': 24,
    'Illusion: Earth Elemental': 24,
    'Illusion: Skeleton': 24,
    'Invigor': 24,
    'Major Shielding': 24,
    'Rune II': 24,
    "Sagar`s Animation": 24,
    'Strip Enchantment': 24,
    'Tepid Deeds': 24,
    'Augmentation': 29,
    'Clarify Mana': 29,
    'Clarity': 29,
    'Curse of the Simple Mind': 29,
    "Dyn`s Dizzying Draught": 29,
    'Enstill': 29,
    'Feedback': 29,
    'Illusion: Air Elemental': 29,
    'Illusion: Water Elemental': 29,
    'Listless Power': 29,
    'Nullify Magic': 29,
    'Obscure': 29,
    'Suffocate': 29,
    "Uleen`s Animation": 29,
    'Ultravision': 29,
    'Anarchy': 34,
    "Boltran`s Animation": 34,
    'Cast Sight': 34,
    'Enchant Platinum': 34,
    'Entrance': 34,
    'Gift of Magic': 34,
    'Greater Shielding': 34,
    'Illusion: Fire Elemental': 34,
    'Insipid Weakness': 34,
    'Mana Sieve': 34,
    'Radiant Visage': 34,
    'Rune III': 34,
    "Aanya's Animation": 39,
    'Cajoling Whispers': 39,
    'Celerity': 39,
    'Distill Mana': 39,
    'Gravity Flux': 39,
    'Illusion: Dry Bone': 39,
    'Illusion: Spirit Wolf': 39,
    'Immobilize': 39,
    'Insight': 39,
    'Invoke Fear': 39,
    'Mind Wipe': 39,
    'Pacify': 39,
    'Rampage': 39,
    'Resist Magic': 39,
    'Shade': 39,
    'Wandering Mind': 39,
    'Arch Shielding': 44,
    'Boon of the Garou': 44,
    'Brilliance': 44,
    'Color Skew': 44,
    'Discordant Mind': 44,
    'Enchant Velium': 44,
    'Extinguish Fatigue': 44,
    'Illusion: Werewolf': 44,
    'Incapacitate': 44,
    'Pillage Enchantment': 44,
    'Rune IV': 44,
    'Shiftless Deeds': 44,
    'Summon Companion': 44,
    'Tashania': 44,
    'Weakness': 44,
    "Yegoreff`s Animation": 44,
    'Adorning Grace': 49,
    'Allure': 49,
    'Berserker Spirit': 49,
    'Blanket of Forgetfulness': 49,
    'Dazzle': 49,
    'Enchant Adamantite': 49,
    'Enchant Brellium': 49,
    'Enchant Mithril': 49,
    'Enchant Steel': 49,
    'Gasping Embrace': 49,
    'Group Resist Magic': 49,
    "Kintaz`s Animation": 49,
    'Paralyzing Earth': 49,
    'Purify Mana': 49,
    'Reoccurring Amnesia': 49,
    'Shadow': 49,
    'Swift like the Wind': 49,
    'Improved Invisibility': 50,
    'Collaboration': 51,
    'Theft of Thought': 51,
    'Wake of Tranquility': 51,
    'Boon of the Clear Mind': 52,
    'Color Slant': 52,
    'Fascination': 52,
    'Rune V': 52,
    "Aanya's Quickening": 53,
    "Boltran`s Agacerie": 53,
    'Cripple': 53,
    'Recant Magic': 53,
    'Clarity II': 54,
    'Dementia': 54,
    'Glamour of Kintaz': 54,
    'Shield of the Magi': 54,
    'Gift of Insight': 55,
    "Largarn's Lamentation": 55,
    'Memory Flux': 55,
    'Wind of Tishani': 55,
    "Zumaik`s Animation": 55,
    'Augment': 56,
    'Overwhelming Splendor': 56,
    'Torment of Argli': 56,
    'Trepidation': 56,
    'Enlightenment': 57,
    'Forlorn Deeds': 57,
    'Tashanian': 57,
    'Umbra': 57,
    'Bedlam': 58,
    'Fetter': 58,
    'Wonderous Rapidity': 58,
    'Asphyxiate': 59,
    'Gift of Pure Thought': 59,
    'Rapture': 59,
    'Dictate': 60,
    'Gift of Brilliance': 60,
    'Visions of Grandeur': 60,
    'Wind of Tishanian': 60
  },
  mage: {
    'Burst of Flame': 1,
    'Flare': 1,
    'Minor Shielding': 1,
    'Reclaim Energy': 1,
    'Summon Dagger': 1,
    'Summon Drink': 1,
    'Summon Food': 1,
    'True North': 1,
    'Burn': 4,
    'Elementalkin: Air': 4,
    'Elementalkin: Earth': 4,
    'Elementalkin: Fire': 4,
    'Elementalkin: Water': 4,
    'Fire Flux': 4,
    'Gate': 4,
    'Sense Summoned': 4,
    'Summon Bandages': 4,
    'Summon Wisp': 4,
    'Dimensional Pocket': 8,
    'Elementaling: Air': 8,
    'Elementaling: Earth': 8,
    'Elementaling: Fire': 8,
    'Elementaling: Water': 8,
    'Eye of Zomm': 8,
    'Flame Bolt': 8,
    'Invisibility': 8,
    'Lesser Shielding': 8,
    'Renew Elements': 8,
    'Shield of Fire': 8,
    'Shock of Blades': 8,
    'Staff of Tracing': 8,
    'Bind Affinity': 12,
    'Burnout': 12,
    'Cancel Magic': 12,
    'Column of Fire': 12,
    'Elemental: Air': 12,
    'Elemental: Earth': 12,
    'Elemental: Fire': 12,
    'Elemental: Water': 12,
    'Rain of Blades': 12,
    'Summon Fang': 12,
    'Ward Summoned': 12,
    'Identify': 16,
    'Minor Summoning: Air': 16,
    'Minor Summoning: Earth': 16,
    'Minor Summoning: Fire': 16,
    'Minor Summoning: Water': 16,
    'Phantom Leather': 16,
    'See Invisible': 16,
    'Shielding': 16,
    'Shock of Flame': 16,
    'Staff of Warding': 16,
    'Summon Heatstone': 16,
    'Summon Throwing Dagger': 16,
    'Bolt of Flame': 20,
    'Elemental Shield': 20,
    'Expulse Summoned': 20,
    'Lesser Summoning: Air': 20,
    'Lesser Summoning: Earth': 20,
    'Lesser Summoning: Fire': 20,
    'Lesser Summoning: Water': 20,
    'Rain of Fire': 20,
    'Renew Summoning': 20,
    'Shield of Flame': 20,
    'Spear of Warding': 20,
    'Summon Arrows': 20,
    'Summon Waterstone': 20,
    'Cornucopia': 24,
    'Everfount': 24,
    'Flame Flux': 24,
    'Major Shielding': 24,
    'Malaise': 24,
    'Shock of Spikes': 24,
    'Staff of Runes': 24,
    'Summoning: Air': 24,
    'Summoning: Earth': 24,
    'Summoning: Fire': 24,
    'Summoning: Water': 24,
    'Burnout II': 29,
    'Dismiss Summoned': 29,
    'Expedience': 29,
    'Greater Summoning: Air': 29,
    'Greater Summoning: Earth': 29,
    'Greater Summoning: Fire': 29,
    'Greater Summoning: Water': 29,
    'Inferno Shield': 29,
    'Phantom Chain': 29,
    'Rain of Spikes': 29,
    'Summon Coldstone': 29,
    'Sword of Runes': 29,
    'Blaze': 34,
    'Cinder Bolt': 34,
    'Dimensional Hole': 34,
    'Greater Shielding': 34,
    'Minor Conjuration: Air': 34,
    'Minor Conjuration: Earth': 34,
    'Minor Conjuration: Fire': 34,
    'Minor Conjuration: Water': 34,
    'Monster Summoning I': 34,
    'Nullify Magic': 34,
    'Staff of Symbols': 34,
    'Summon Shard of the Core': 34,
    'Barrier of Combustion': 39,
    'Dagger of Symbols': 39,
    'Expel Summoned': 39,
    'Flame Arc': 39,
    'Lesser Conjuration: Air': 39,
    'Lesser Conjuration: Earth': 39,
    'Lesser Conjuration: Fire': 39,
    'Lesser Conjuration: Water': 39,
    'Rain of Lava': 39,
    'Summon Companion': 39,
    'Summon Ring of Flight': 39,
    'Arch Shielding': 44,
    'Conjuration: Air': 44,
    'Conjuration: Earth': 44,
    'Conjuration: Fire': 44,
    'Conjuration: Water': 44,
    'Elemental Armor': 44,
    'Elemental Maelstrom': 44,
    'Malaisement': 44,
    'Modulating Rod': 44,
    'Phantom Plate': 44,
    'Shock of Swords': 44,
    'Summon Orb': 46,
    'Banish Summoned': 49,
    'Burnout III': 49,
    'Greater Conjuration: Air': 49,
    'Greater Conjuration: Earth': 49,
    'Greater Conjuration: Fire': 49,
    'Greater Conjuration: Water': 49,
    'Lava Bolt': 49,
    'Rain of Swords': 49,
    'Shield of Lava': 49,
    'Monster Summoning II': 50,
    'Gift of Xev': 51,
    'Malosi': 51,
    'Scintillation': 51,
    'Vocarate: Earth': 51,
    "Bristlebane's Bundle": 52,
    'Char': 52,
    'Phantom Armor': 52,
    'Vocarate: Fire': 52,
    'Annul Magic': 53,
    'Boon of Immolation': 53,
    'Quiver of Marr': 53,
    'Vocarate: Air': 53,
    'Bandoleer of Luclin': 53,
    'Scars of Sigil': 54,
    'Shield of the Magi': 54,
    'Vocarate: Water': 54,
    'Burnout IV': 55,
    'Call of the Hero': 55,
    'Pouch of Quellious': 55,
    'Rage of Zomm': 55,
    'Sirocco': 55,
    'Wrath of the Elements': 55,
    'Cadeau of Flame': 56,
    "Dyzil's Deafening Decoy": 56,
    'Exile Summoned': 56,
    'Muzzle of Mardu': 56,
    'Eye of Tallon': 57,
    'Greater Vocaration: Earth': 57,
    'Shock of Steel': 57,
    'Greater Vocaration: Fire': 58,
    'Malosini': 58,
    'Velocity': 58,
    'Greater Vocaration: Air': 59,
    'Manastorm': 59,
    'Seeking Flame of Seukor': 59,
    'Valiant Companion': 59,
    'Aegis of Ro': 60,
    'Banishment': 60,
    'Greater Vocaration: Water': 60,
    'Mala': 60,
    'Monster Summoning III': 60
  },
  necromancer: {
    'Cavorting Bones': 1,
    'ColdLight': 1,
    'Disease Cloud': 1,
    'Invisibility versus Undead': 1,
    'Lifetap': 1,
    'Locate Corpse': 1,
    'Minor Shielding': 1,
    'Reclaim Energy': 1,
    'Sense the Dead': 1,
    'Siphon Strength': 1,
    'Clinging Darkness': 4,
    'Endure Cold': 4,
    'Fear': 4,
    'Gate': 4,
    'Grim Aura': 4,
    'Leering Corpse': 4,
    'Lifespike': 4,
    'Numb the Dead': 4,
    'Poison Bolt': 4,
    'True North': 4,
    'Bone Walk': 8,
    'Dark Empathy': 8,
    'Dark Pact': 8,
    'Deadeye': 8,
    'Gather Shadows': 8,
    'Impart Strength': 8,
    'Lesser Shielding': 8,
    'Mend Bones': 8,
    'Shadow Step': 8,
    'Vampiric Embrace': 8,
    'Ward Undead': 8,
    'Bind Affinity': 12,
    'Convoke Shadow': 12,
    'Endure Disease': 12,
    'Engulfing Darkness': 12,
    'Heat Blood': 12,
    'Leach': 12,
    'Lifedraw': 12,
    'Scent of Dusk': 12,
    'Sight Graft': 12,
    'Spook the Dead': 12,
    'Wave of Enfeeblement': 12,
    'Banshee Aura': 16,
    'Cancel Magic': 16,
    'Cure Disease': 16,
    'Feign Death': 16,
    'Heart Flutter': 16,
    'Hungry Earth': 16,
    'Infectious Cloud': 16,
    'Restless Bones': 16,
    'Shielding': 16,
    'Shieldskin': 16,
    'Spirit Armor': 16,
    'Voice Graft': 16,
    'Allure of Death': 20,
    'Animate Dead': 20,
    'Dominate Undead': 20,
    'Expulse Undead': 20,
    'Harmshield': 20,
    'Identify': 20,
    'Shadow Compact': 20,
    'Shadow Vortex': 20,
    'Siphon Life': 20,
    'Track Corpse': 20,
    'Word of Shadow': 20,
    'Breath of the Dead': 24,
    'Haunting Corpse': 24,
    'Intensify Death': 24,
    'Leatherskin': 24,
    'Major Shielding': 24,
    'Rapacious Subversion': 24,
    'Resist Cold': 24,
    'Rest the Dead': 24,
    'Scent of Shadow': 24,
    'Screaming Terror': 24,
    'Shadow Sight': 24,
    'Shock of Poison': 24,
    'Boil Blood': 29,
    'Dismiss Undead': 29,
    'Dooming Darkness': 29,
    'Panic the Dead': 29,
    'Renew Bones': 29,
    'Spirit Tap': 29,
    'Summon Dead': 29,
    'Vampiric Curse': 29,
    'Word of Spirit': 29,
    'Beguile Undead': 34,
    'Call of Bones': 34,
    'Greater Shielding': 34,
    'Invoke Fear': 34,
    'Invoke Shadow': 34,
    'Resist Disease': 34,
    'Root': 34,
    'Steelskin': 34,
    'Surge of Enfeeblement': 34,
    "Torbas' Acid Blast": 34,
    'Venom of the Snake': 34,
    'Augment Death': 39,
    'Chilling Embrace': 39,
    'Counteract Disease': 39,
    'Drain Spirit': 39,
    'Expel Undead': 39,
    'Malignant Dead': 39,
    'Nullify Magic': 39,
    'Scent of Darkness': 39,
    'Scourge': 39,
    'Summon Corpse': 39,
    'Word of Souls': 39,
    'Arch Shielding': 44,
    'Asystole': 44,
    'Cackling Bones': 44,
    'Corporeal Empathy': 44,
    'Covetous Subversion': 44,
    'Dead Man Floating': 44,
    'Diamondskin': 44,
    'Ignite Bones': 44,
    'Incinerate Bones': 44,
    'Pact of Shadow': 44,
    'Summon Companion': 44,
    'Banish Undead': 49,
    'Bond of Death': 49,
    'Cajole Undead': 49,
    'Cascading Darkness': 49,
    'Dead Men Floating': 49,
    'Drain Soul': 49,
    'Ignite Blood': 49,
    'Invoke Death': 49,
    'Lich': 49,
    'Paralyzing Earth': 49,
    'Improved Invis vs Undead': 50,
    'Dread of Night': 51,
    'Envenomed Bolt': 51,
    'Sacrifice': 51,
    'Splurt': 51,
    'Defoliation': 52,
    'Manaskin': 52,
    'Plague': 52,
    'Scent of Terris': 52,
    'Annul Magic': 53,
    'Convergence': 53,
    'Enstill': 53,
    'Minion of Shadows': 53,
    'Deflux': 54,
    'Shadowbond': 54,
    'Shield of the Magi': 54,
    'Thrall of Bones': 54,
    'Augmentation of Death': 55,
    'Chill Bones': 55,
    'Conglaciation of Bone': 55,
    'Infusion': 55,
    'Levant': 55,
    'Skin of the Shadow': 55,
    'Cessation of Cor': 56,
    'Sedulous Subversion': 56,
    'Servant of Bones': 56,
    'Trepidation': 56,
    'Conjure Corpse': 57,
    'Exile Undead': 57,
    'Vexing Mordinia': 57,
    'Immobilize': 58,
    'Pyrocruor': 58,
    'Quivering Veil of Xarn': 58,
    'Devouring Darkness': 59,
    'Emissary of Thule': 59,
    'Touch of Night': 59,
    'Arch Lich': 60,
    'Banishment of Shadows': 60,
    'Demi Lich': 60,
    'Enslave Death': 60,
    "Gangrenous Touch of Zum'uul": 60,
    'Trucidation': 60
  },
  paladin: {
    'Courage': 9,
    'Cure Poison': 9,
    'Flash of Light': 9,
    'Minor Healing': 9,
    'Spook the Dead': 9,
    'True North': 9,
    'Yaulp': 9,
    'Cure Disease': 15,
    'Hammer of Wrath': 15,
    'Holy Armor': 15,
    'Light Healing': 15,
    'Lull': 15,
    'Sense the Dead': 15,
    'Ward Undead': 15,
    'Center': 22,
    'Endure Poison': 22,
    'Halo of Light': 22,
    'Invigor': 22,
    'Invisibility versus Undead': 22,
    'Reckless Strength': 22,
    'Root': 22,
    'Endure Magic': 30,
    'Expulse Undead': 30,
    'Hammer of Striking': 30,
    'Healing': 30,
    'Soothe': 30,
    'Spirit Armor': 30,
    'Stun': 30,
    'Symbol of Transal': 30,
    'Cancel Magic': 39,
    'Counteract Poison': 39,
    'Daring': 39,
    'Divine Purpose': 39,
    'Endure Disease': 39,
    'Greater Healing': 39,
    'Guard': 39,
    'Symbol of Ryltan': 39,
    'Yaulp II': 39,
    'Armor of Faith': 49,
    'Calm': 49,
    'Dismiss Undead': 49,
    'Divine Might': 49,
    'Holy Might': 49,
    'Revive': 49,
    'Symbol of Pinzarn': 49,
    'Valor': 49,
    'Flame of Light': 50,
    'Pacify': 51,
    'Resist Disease': 51,
    'Force': 52,
    'Frenzied Strength': 52,
    'Divine Glory': 53,
    'Enstill': 54,
    'Expel Undead': 54,
    'Divine Aura': 55,
    'Divine Favor': 55,
    'Resist Magic': 55,
    'Wave of Healing': 55,
    'Counteract Disease': 56,
    'Yaulp III': 56,
    'Superior Healing': 57,
    'Nullify Magic': 58,
    'Symbol of Naltron': 58,
    'Celestial Cleansing': 59,
    'Resurrection': 59,
    'Divine Strength': 60,
    'Resolution': 60,
    'Shield of Words': 60,
    'Yaulp IV': 60
  },
  ranger: {
    'Endure Fire': 9,
    'Flame Lick': 9,
    'Glimpse': 9,
    'Lull Animal': 9,
    'Minor Healing': 9,
    'Skin like Wood': 9,
    'Snare': 9,
    'Burst of Fire': 15,
    'Camouflage': 15,
    'Cure Poison': 15,
    'Dance of the Fireflies': 15,
    'Feet like Cat': 15,
    'Grasping Roots': 15,
    'Invoke Lightning': 15,
    'Thistlecoat': 15,
    'Bind Sight': 22,
    'Endure Cold': 22,
    'Enduring Breath': 22,
    'Firefist': 22,
    'Harmony': 22,
    'Ignite': 22,
    'Light Healing': 22,
    'Panic Animal': 22,
    'Skin like Rock': 22,
    'Ward Summoned': 22,
    'Barbcoat': 30,
    'Cancel Magic': 30,
    'Eyes of the Cat': 30,
    'Invigor': 30,
    'Shield of Thistles': 30,
    'Spirit of Wolf': 30,
    'Stinging Swarm': 30,
    'Strength of Earth': 30,
    'Bramblecoat': 39,
    'Call of Sky': 39,
    'Calm Animal': 39,
    'Careless Lightning': 39,
    'Dismiss Summoned': 39,
    'Healing': 39,
    'Levitate': 39,
    'See Invisible': 39,
    'Skin like Steel': 39,
    'Call of Flame': 49,
    'Ensnaring Roots': 49,
    'Immolate': 49,
    'Resist Fire': 49,
    'Shield of Brambles': 49,
    'Spikecoat': 49,
    'Wolf Form': 49,
    'Call of Earth': 50,
    'Ensnare': 51,
    'Jolt': 51,
    'Strength of Nature': 51,
    'Extinguish Fatigue': 52,
    'Firestrike': 52,
    'Storm Strength': 53,
    'Drones of Doom': 54,
    'Skin like Diamond': 54,
    'Call of Fire': 55,
    'Chloroplast': 55,
    'Cinder Jolt': 55,
    'Resist Cold': 55,
    'Chill Sight': 56,
    'Greater Wolf Form': 56,
    'Greater Healing': 57,
    'Nullify Magic': 58,
    'Shield of Spikes': 58,
    'Calefaction': 59,
    'Skin like Nature': 59,
    'Call of the Predator': 60,
    'Enveloping Roots': 60,
    'Thorncoat': 60
  },
  shadowknight: {
    'Disease Cloud': 9,
    'Invisibility versus Undead': 9,
    'Leering Corpse': 9,
    'Lifetap': 9,
    'Locate Corpse': 9,
    'Sense the Dead': 9,
    'Siphon Strength': 9,
    'Bone Walk': 15,
    'Clinging Darkness': 15,
    'Endure Cold': 15,
    'Fear': 15,
    'Lifespike': 15,
    'Numb the Dead': 15,
    'Shadow Step': 15,
    'Convoke Shadow': 22,
    'Dark Empathy': 22,
    'Deadeye': 22,
    'Engulfing Darkness': 22,
    'Grim Aura': 22,
    'Spook the Dead': 22,
    'Vampiric Embrace': 22,
    'Ward Undead': 22,
    'Strengthen Death': 29,
    'Endure Disease': 30,
    'Feign Death': 30,
    'Gather Shadows': 30,
    'Heat Blood': 30,
    'Lifedraw': 30,
    'Restless Bones': 30,
    'Wave of Enfeeblement': 30,
    'Shieldskin': 34,
    'Animate Dead': 39,
    'Cancel Magic': 39,
    'Expulse Undead': 39,
    'Heart Flutter': 39,
    'Resist Cold': 39,
    'Shadow Vortex': 39,
    'Shroud of Hate': 39,
    'Breath of the Dead': 49,
    'Dismiss Undead': 49,
    'Dooming Darkness': 49,
    'Invoke Fear': 49,
    'Life Leech': 49,
    'Shadow Sight': 49,
    'Summon Dead': 49,
    'Word of Spirit': 49,
    'Shroud of Pain': 50,
    'Siphon Life': 51,
    'Summon Corpse': 51,
    'Malignant Dead': 52,
    'Summon Companion': 52,
    'Rest the Dead': 52,
    'Boil Blood': 53,
    'Banshee Aura': 54,
    'Panic the Dead': 54,
    'Bobbing Corpse': 55,
    'Expel Undead': 55,
    'Shroud of Death': 55,
    'Shroud of Undeath': 55,
    'Spirit Tap': 55,
    'Steelskin': 56,
    'Drain Spirit': 57,
    'Vampiric Curse': 57,
    'Cackling Bones': 58,
    'Nullify Magic': 58,
    'Cascading Darkness': 59,
    'Diamondskin': 59,
    'Asystole': 60,
    'Drain Soul': 60,
    'Death Peace': 60
  },
  shaman: {
      "Burst of Flame": 1,
      "Cure Disease": 1,
      "Dexterous Aura": 1,
      "Endure Cold": 1,
      "Flash of Light": 1,
      "Inner Fire": 1,
      "Minor Healing": 1,
      "Strengthen": 1,
      "True North": 1,
      "Cure Poison": 5,
      "Drowsy": 5,
      "Endure Fire": 5,
      "Feet like Cat": 5,
      "Fleeting Fury": 5,
      "Frost Rift": 5,
      "Gate": 5,
      "Scale Skin": 5,
      "Sicken": 5,
      "Spirit Pouch": 5,
      "Summon Drink": 5,
      "Cure Blindness": 9,
      "Endure Disease": 9,
      "Light Healing": 9,
      "Sense Animals": 9,
      "Serpent Sight": 9,
      "Spirit of Bear": 9,
      "Spirit of Wolf": 9,
      "Spirit Sight": 9,
      "Summon Food": 9,
      "Tainted Breath": 9,
      "Bind Affinity": 14,
      "Burst of Strength": 14,
      "Disempower": 14,
      "Endure Poison": 14,
      "Enduring Breath": 14,
      "Invisibility versus Animals": 14,
      "Levitate": 14,
      "Root": 14,
      "Spirit of Snake": 14,
      "Spirit Strike": 14,
      "Turtle Skin": 14,
      "Walking Sleep": 14,
      "Affliction": 19,
      "Cancel Magic": 19,
      "Endure Magic": 19,
      "Frenzy": 19,
      "Healing": 19,
      "Infectious Cloud": 19,
      "Insidious Fever": 19,
      "Malaise": 19,
      "Shrink": 19,
      "Spirit of Cat": 19,
      "Spirit Strength": 19,
      "Vision": 19,
      "Cannibalize": 24,
      "Counteract Disease": 24,
      "Creeping Vision": 24,
      "Envenomed Breath": 24,
      "Frost Strike": 24,
      "Invigor": 24,
      "Poison Storm": 24,
      "Protect": 24,
      "Regeneration": 24,
      "Resist Cold": 24,
      "Spirit of Cheetah": 24,
      "Spirit of Monkey": 24,
      "Spirit of Ox": 24,
      "Scale of Wolf": 24,
      "Alluring Aura": 29,
      "Befriend Animal": 29,
      "Counteract Poison": 29,
      "Greater Healing": 29,
      "Imbue Amber": 29,
      "Imbue Ivory": 29,
      "Imbue Jade": 29,
      "Imbue Sapphire": 29,
      "Invisibility": 29,
      "Listless Power": 29,
      "Quickness": 29,
      "Raging Strength": 29,
      "Resist Fire": 29,
      "Rising Dexterity": 29,
      "Tagar's Insects": 29,
      "Ultravision": 29,
      "Charm Animals": 34,
      "Companion Spirit": 34,
      "Enstill": 34,
      "Fury": 34,
      "Health": 34,
      "Malaisement": 34,
      "Nimble": 34,
      "Resist Disease": 34,
      "Scourge Disease": 34,
      "Shifting Shield": 34,
      "Shock of the Tainted": 34,
      "Talisman of Tnarg": 34,
      "Winter's Roar": 34,
      "Assiduous Vision": 39,
      "Blinding Luminance": 39,
      "Cannibalize II": 39,
      "Chloroplast": 39,
      "Deftness": 39,
      "Extinguish Fatigue": 39,
      "Furious Strength": 39,
      "Gale of Poison": 39,
      "Glamour": 39,
      "Insidious Malady": 39,
      "Resist Poison": 39,
      "Togor's Insects": 39,
      "Tumultuous Strength": 39,
      "Venom of the Snake": 39,
      "Vigilant Spirit": 39,
      "Agility": 44,
      "Alacrity": 44,
      "Blast of Poison": 44,
      "Blizzard Blast": 44,
      "Guardian": 44,
      "Guardian Spirit": 44,
      "Incapacitate": 44,
      "Nullify Magic": 44,
      "Resist Magic": 44,
      "Stamina": 44,
      "Summon Companion": 44,
      "Talisman of Altuna": 44,
      "Abolish Disease": 49,
      "Charisma": 49,
      "Dexterity": 49,
      "Envenomed Bolt": 49,
      "Frenzied Spirit": 49,
      "Malosi": 49,
      "Plague": 49,
      "Rage": 49,
      "Strength": 49,
      "Spirit Quickening": 50,
      "Superior Healing": 51,
      "Immobilize": 51,
      "Talisman of Jasinth": 51,
      "Turgur's Insects": 51,
      "Insidious Decay": 52,
      "Regrowth": 52,
      "Spirit of Scale": 52,
      "Cripple": 53,
      "Deliriously Nimble": 53,
      "Superior Healing": 53,
      "Talisman of Shadoo": 53,
      "Cannibalize III": 54,
      "Ice Strike": 54,
      "Riotous Health": 54,
      "Shroud of the Spirits": 54,
      "Annul Magic": 55,
      "Chloroblast": 55,
      "Form of the Great Bear": 55,
      "Spirit of the Howler": 55,
      "Talisman of Kragg": 55,
      "Torrent of Poison": 55,
      "Acumen": 56,
      "Bane of Nife": 56,
      "Celerity": 56,
      "Paralyzing Earth": 56,
      "Malosini": 57,
      "Manicial Strength": 57,
      "Talisman of the Brute": 57,
      "Talisman of the Cat": 57,
      "Cannibalize IV": 58,
      "Mortal Deftness": 58,
      "Talisman of the Rhino": 58,
      "Talisman of the Serpent": 58,
      "Tigir's Insects": 58,
      "Pox of Bertoxxulous": 59,
      "Talisman of the Raptor": 59,
      "Unfailing Reverence": 59,
      "Voice of the Berserker": 59,
      "Avatar": 60,
      "Focus of Spirit": 60,
      "Malo": 60,
      "Primal Avatar": 60,
      "Torpor": 60
  
  },
  wizard: {
    'Frost Bolt': 1,
    'Minor Shielding': 1,
    'Numbing Cold': 1,
    'Shock of Frost': 1,
    'Sphere of Light': 1,
    'True North': 1,
    'Fade': 4,
    'Gate': 4,
    'Glimpse': 4,
    'Icestrike': 4,
    "O'Keils Radiation": 4,
    'Root': 4,
    'See Invisible': 4,
    'Shock of Fire': 4,
    'Column of Frost': 8,
    'Eye of Zomm': 8,
    'Fingers of Fire': 8,
    'Fire Bolt': 8,
    'Lesser Shielding': 8,
    'Sense Summoned': 8,
    'Shadow Step': 8,
    'Shock of Ice': 8,
    'Bind Affinity': 12,
    'Cancel Magic': 12,
    'Firestorm': 12,
    "Frost Spiral of Al'Kabor": 12,
    'Gaze': 12,
    'Halo of Light': 12,
    'Resistant Skin': 12,
    'Shock of Lightning': 12,
    'Bind Sight': 16,
    'Flame Shock': 16,
    'Heat Sight': 16,
    'Identify': 16,
    'Invisibility': 16,
    'Lightning Bolt': 16,
    'Pillar of Fire': 16,
    'Project Lightning': 16,
    'Shielding': 16,
    'Shieldskin': 16,
    'Elemental Shield': 20,
    'Enstill': 20,
    'Fay Gate': 20,
    "Fire Spiral of Al'Kabor": 20,
    'Force Shock': 20,
    'North Gate': 20,
    'Sight': 20,
    "Tishan's Clash": 20,
    'Tox Gate': 20,
    'Cast Force': 24,
    'Cazic Gate': 24,
    'Column of Lightning': 24,
    'Combine Gate': 24,
    'Common Gate': 24,
    'Frost Shock': 24,
    'Leatherskin': 24,
    'Levitate': 24,
    'Lightning Storm': 24,
    'Major Shielding': 24,
    'Nek Gate': 24,
    'Ro Gate': 24,
    'West Gate': 24,
    'Bonds of Force': 29,
    'Energy Storm': 29,
    'Evacuate: North': 29,
    'Fay Portal': 29,
    'Imbue Fire Opal': 29,
    'Inferno Shock': 29,
    'Magnify': 29,
    'North Portal': 29,
    "Shock Spiral of Al'Kabor": 29,
    'Thunder Strike': 29,
    'Tox Portal': 29,
    'Yonder': 29,
    'Cazic Portal': 34,
    'Circle of Force': 34,
    'Combine Portal': 34,
    'Evacuate: Fay': 34,
    'Great Divide Gate': 34,
    'Greater Shielding': 34,
    'Harvest': 34,
    'Ice Shock': 34,
    'Iceclad Gate': 34,
    'Iceclad Portal': 34,
    'Lava Storm': 34,
    'Nek Portal': 34,
    'Nullify Magic': 34,
    "O'Keils Flickering Flame": 34,
    'Steelskin': 34,
    'Thunderclap': 34,
    'Chill Sight': 39,
    'Cobalt Scar Gate': 39,
    'Common Portal': 39,
    'Concussion': 39,
    'Evacuate: Ro': 39,
    "Force Spiral of Al'Kabor": 39,
    'Great Divide Portal': 39,
    'Immobilize': 39,
    'Invisibility to Undead': 39,
    'Lightning Shock': 39,
    "Markar's Relocation": 39,
    'Ro Portal': 39,
    'Shifting Sight': 39,
    "Tishan's Relocation": 39,
    'Translocate: Combine': 39,
    'Translocate: Fay': 39,
    'Translocate: North': 39,
    'Translocate: Tox': 39,
    'Wakening Lands Gate': 39,
    'West Portal': 39,
    'Arch Shielding': 44,
    'Cobalt Scar Portal': 44,
    'Conflagration': 44,
    'Diamondskin': 44,
    'Elemental Armor': 44,
    'Enticement of Flame': 44,
    'Evacuate: Nek': 44,
    'Force Strike': 44,
    'Frost Storm': 44,
    'Gravity Flux': 44,
    'Translocate: Cazic': 44,
    'Translocate: Common': 44,
    'Translocate: West': 44,
    'Translocate: Nek': 44,
    'Translocate: Ro': 44,
    'Wakening Lands Portal': 44,
    'Alter Plane: Hate': 46,
    'Alter Plane: Sky': 46,
    'Evacuate: West': 49,
    'Ice Comet': 49,
    "Markar's Clash": 49,
    'Paralyzing Earth': 49,
    'Supernova': 49,
    'Translocate: Cobalt Scar': 49,
    'Translocate: Great Divide': 49,
    'Translocate: Iceclad': 49,
    'Translocate: Wakening Lands': 49,
    "Wrath of Al'Kabor": 49,
    'Translocate': 50,
    "Atol's Spectral Shackles": 51,
    'Draught of Fire': 51,
    'Pillar of Frost': 51,
    "Tishan's Discord": 51,
    'Abscond': 52,
    'Lure of Frost': 52,
    'Manaskin': 52,
    'Tears of Druzzil': 52,
    'Translocate: Group': 52,
    'Annul Magic': 53,
    "Inferno of Al'Kabor": 53,
    "Jyll's Static Pulse": 53,
    'Pillar of Lightning': 54,
    'Shield of the Magi': 54,
    'Thunderbold': 54,
    'Voltaic Draught': 54,
    'Draught of Jiva': 55,
    'Improved Invisibility': 55,
    'Lure of Flame': 55,
    'Plainsight': 55,
    'Tears of Solusek': 55,
    "Jyll's Zephyr of Ice": 56,
    "Markar's Discord": 56,
    "Retribution of Al'Kabor": 56,
    'Draught of Ice': 57,
    'Evacuate': 57,
    'Eye of Tallon': 57,
    'Pillar of Flame': 57,
    'Fetter': 58,
    'Lure of Lightning': 58,
    'Manasink': 58,
    'Tears of Prexus': 58,
    'Flaming Sword of Xuzl': 59,
    'Invert Gravity': 59,
    "Jyll's Wave of Heat": 59,
    "Vengeance of Al'Kabor": 59,
    'Disintegrate': 60,
    "Hsagra's Wrath": 60,
    'Ice Spear of Solist': 60,
    'Lure of Ice': 60,
    "Porlos' Fury": 60,
    'Sunstrike': 60,
    'Winds of Gelid': 60
  }
}
